apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-tweets-cronjob
spec:
  # JST 7:00
  schedule: "0 22 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-tweets
            image: codekakitai51/u-bot-sdk-based:v1
            command: ["python3", "/app/generate_tweets.py"]
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/var/secrets/google/key.json"
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    name: twitter-api-secrets
                    key: API_KEY
              - name: API_KEY_SECRET
                valueFrom:
                  secretKeyRef:
                    name: twitter-api-secrets
                    key: API_KEY_SECRET
              - name: ACCESS_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: twitter-api-secrets
                    key: ACCESS_TOKEN
              - name: ACCESS_TOKEN_SECRET
                valueFrom:
                  secretKeyRef:
                    name: twitter-api-secrets
                    key: ACCESS_TOKEN_SECRET
            volumeMounts:
              - name: google-cloud-key
                mountPath: "/var/secrets/google"
          volumes:
            - name: google-cloud-key
              secret:
                secretName: u-bot-secret-for-storage
          restartPolicy: OnFailure
